---
- hosts: all
  remote_user: root
  task:

     - name: Instalación de paquetes requeridos para levantar el web server.
      action: apt pkg={{ item }} state=installed
      with_items:
        - php5
        - apache2
        - mysql-server
        - mysql-client
        - php5-mysql
        - php-apc
        - php5-xmlrpc
        - php-soap
        - php5-gd
        - unzip
        - python-mysqldb


    - name: Habilitar módulos de Apache
      action: command a2enmod rewrite vhost_alias

    
    - name: Reiniciar Apache
      action: service name=apache2 state=restarted

    